### ISSUE TITLE
Page title showing on node and term 403/404's

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/rabbit_hole#2]
It seems that the content or term title still displays for nodes and terms (but not users) when set to show a 403 or 404 page, which doesn't seem great.

**Comment by herbdool** [comment]
How does it look in D7 compared to BD?

**Comment by olafgrabienski** [comment]
Just tested for nodes: Using Drupal 7.56 and Rabbit Hole 7.x-2.24, the node page title is not displayed. Instead, the page title is "Page not found" for a 404 page.

**Comment by laryn** [comment]
This could be fixed by adding a `backdrop_set_title()` in the module where it is delivering the 404 or 403, but I'm not sure if that's the right way or if this means there's a deeper core issue that should be resolved in `backdrop_access_denied()` or `backdrop_not_found()`.

**Comment by herbdool** [comment]
I think it's a sign of a deeper issue

**Comment by laryn** [comment]
@herbdool Agreed. I'll create a core issue to get more input on where to fix it.

**Comment by laryn** [comment]
I may have committed that prematurely.

**Comment by herbdool** [comment]
Since you don't have any releases yet it's not a big deal.

**Comment by serundeputy** [comment]
maybe since we have page title in the layout as a 'block' (not sure it is really a block) that is rendering from the layout layer even though the entity is calling `backdrop_access_denied()`?

If that is true than RH will need to interact with the layout system some how, some way. I'm just speculating though.

**Comment by herbdool** [comment]
If true than any module calling backdrop_access_denied() would have the same problem, no?

**Comment by serundeputy** [comment]
I called it from a custom module and it worked as expected, but I'm not sure if a custom module with a page callback uses the layout system or not

**Comment by herbdool** [comment]
I suppose it's good news that it's not a core issue.

Maybe it's a problem of calling backdrop_access_denied() from hook_node_view()? That seems to be all Rabbit Hole is doing. Nothing else fancy going on.

**Comment by olafgrabienski** [comment]
> I suppose it's good news that it's not a core issue.

@herbdool So, would @laryn 's approach from https://github.com/backdrop-contrib/rabbit_hole/issues/2#issuecomment-351470016 be the way to go again?

**Comment by herbdool** [comment]
Now I'm thinking again this might be better to fix in core. I created a module with only this:

```
function mymodule_node_view($node, $view_mode, $langcode) {
  backdrop_access_denied();
}
```

Since this was working in Drupal 7, we could consider this a regression in Backdrop core and the fix might need to be there. Or find a different hook.

**Comment by jenlampton** [comment]
I'd recommend adding a call to `backdrop_set_title()` into the module right away, to fix the bug. But add a code comment that links to https://github.com/backdrop/backdrop-issues/issues/2918 so that if we do find a deeper issue with core that needs to be fixed, we can remove the fix that was added into Rabbit Hole after that issue is resolved.

**Comment by laryn** [comment]
Workaround is in place with a note about the core issue. Closing this issue for now.
